"""business table

Revision ID: 44904c385174
Revises: f8ea37d6314e
Create Date: 2024-06-28 14:25:20.019989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44904c385174'
down_revision = 'f8ea37d6314e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=64), nullable=False),
    sa.Column('business', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_business'), ['business'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_person'), ['person'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_person'))
        batch_op.drop_index(batch_op.f('ix_business_business'))

    op.drop_table('business')
    # ### end Alembic commands ###
