"""order table

Revision ID: e66d783114ef
Revises: eaacd9fdb975
Create Date: 2024-06-28 17:28:37.921190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66d783114ef'
down_revision = 'eaacd9fdb975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_order_person')
        batch_op.create_index(batch_op.f('ix_order_name'), ['name'], unique=False)
        batch_op.drop_column('person')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_order_name'))
        batch_op.create_index('ix_order_person', ['person'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
