"""order table

Revision ID: eaacd9fdb975
Revises: 44904c385174
Create Date: 2024-06-28 16:46:45.887175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaacd9fdb975'
down_revision = '44904c385174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=64), nullable=False),
    sa.Column('business', sa.String(length=64), nullable=False),
    sa.Column('order', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_person'), ['person'], unique=False)

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index('ix_business_business')
        batch_op.drop_index('ix_business_person')

    op.drop_table('business')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('person', sa.VARCHAR(length=64), nullable=False),
    sa.Column('business', sa.VARCHAR(length=64), nullable=False),
    sa.Column('time', sa.VARCHAR(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index('ix_business_person', ['person'], unique=False)
        batch_op.create_index('ix_business_business', ['business'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_person'))

    op.drop_table('order')
    # ### end Alembic commands ###
